language: node_js
node_js:
  - "10"
env:
  - NODE_ENV=ci  jwtSecretKey=jwtFakeKey vtokenKey=vtokenFakeKey connectionString=postgres://user:password@localhost:5432/postgres

install:
  - npm install

script:
  - npm run test

warnings_are_errors: false
