language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "10"
env:
  - NODE_ENV=ci  jwtSecretKey=jwtFakeKey vtokenKey=FakeFakeFakeFakeFakeFakeFakeFake connectionString=postgres://user:password@localhost:5432/postgres googleClientID_business=ci googleClientSecret_business=ci googleClientID_personal=ci googleClientSecret_personal=ci

install:
  - npm install

script:
  - npm run test

warnings_are_errors: false
